### ISSUE TITLE
Study Week 2

### ISSUE THREAD

**Issue by florayuan18** [florayuan18/just-to-suffer#7]
Points

Extra Credit for Acting/Skit/Improv ASI:  0 to +2 in Seed, -1 for not participating.
GH Indi Page, Review Ticket, Crossover graded 

- [ ] MCQ results > 50%, (1 or 0)
- [ ] FRQs results > 50% (1 or 0), evaluation considers Paper code pictures vs REPL running code. 
- [ ] PBL (0, .5, .75, 1).
 

Scoring guidelines for crossover graders 4.5/5.0 maximum

- [ ] 3 points, use bullets as indicated above, 1 point per sub-bullet
- [ ] 1 point, Participation: .20 for classroom presence and participation each day   
- [ ] .5 point, Quality of work:  grader should be looking at effort toward learning and understanding vs perfunctory bullet chasing (0, .25, .5).

[Link ](http://blog.umbrellabox.cf/2022-05-03-studyweek2/)to all

**Comment by sarahwxie** [comment]
4.25/5
**Grading**
- MCQ results > 50%, (1 or 0) and corrections (1/1)
     - MCQ taken with corrections
- FRQs not taken (not test taker) (1/1)
     - not a test taker, so automatic full!
- Ticket + GitHub (1/1)
     - The ticket is detailed with the required tangible links
- Participation (1/1)
     - Flora was a warm body :)
- Quality of Work (0.25/0.5)
     - The GitHub page would benefit from some increased organization, however overall has all the available links and has a suitable theme.


**Reflections**
- MCQ is completed, and corrections are also completed
- FRQ isn't needed, not a test taker
- All the links are centralized to a single location
- Review ticket is well organized
- Commits are named well, described,  and work towards the central goal of the PBL

I removed 0.25 points because the quality of work is not perfect on the GitHub. The organization could be better.
